### ISSUE TITLE
Label with value "true" removes all the labels in a SveltosCluster created via EventTrigger

### ISSUE THREAD

**Issue by AndreaValerio17** [projectsveltos/event-manager#361]
# Problem Description
In our setup, we use the following `EventSource`, `EventTrigger`, and `ConfigMap` to create a `SveltosCluster` based on a `KamajiControlPlane` resource:

```
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventSource
metadata:
  name: kamaji-tenant-control-plane
spec:
  collectResources: true
  resourceSelectors:
  - group: kamaji.clastix.io
    version: v1alpha1
    kind: TenantControlPlane
---
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventTrigger
metadata:
  name: kamaji-tenant-control-plane
spec:
  sourceClusterSelector:
    matchLabels:
      profile: management
  eventSourceName: kamaji-tenant-control-plane
  oneForEvent: true
  policyRefs:
  - name: register-kamaji-tenant-control-plane
    namespace: projectsveltos 
    kind: ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: register-kamaji-tenant-control-plane
  namespace: projectsveltos
  annotations:
    projectsveltos.io/instantiate: ok
data:
  sveltos-cluster.yaml: |
    apiVersion: lib.projectsveltos.io/v1beta1
    kind: SveltosCluster
    metadata:
      name: {{ .Resource.metadata.name }}
      namespace: {{ .Resource.metadata.namespace }}
      {{- if (index .Resource.metadata `labels`) -}}
      labels:
        {{ range $key, $value := .Resource.metadata.labels }}
        {{ $key }}: {{ $value }}
        {{ end }}
      {{- end -}}
    spec:
      kubeconfigName: {{ .Resource.metadata.name }}-admin-kubeconfig
      kubeconfigKeyName: admin.svc
```
Adding a label with '"true" (forcing the value `true` with quotes to be a string ) as value (e.g., ingress-nginx: "true") to a KamajiControlPlane resource that matches the EventSource configuration seems to break this system. Specifically, it appears to **cause the removal of all existing labels** from the generated SveltosCluster.

## Expected Behavior

Adding that specific kind of label should preserve existing labels.

## Current Behavior

Adding a label with "true" to the KamajiControlPlane results in the SveltosCluster losing its labels.

## Steps to Reproduce

- Deploy Sveltos Event Manager and the EventSource, EventTrigger, and ConfigMap shown above.
- Create a KamajiControlPlane resource in the cluster selected by the sourceClusterSelector of the EventTrigger.
-  Observe that a SveltosCluster is created with labels correctly propagated from the KamajiControlPlane.
- Add a new label (e.g., ingress-nginx: "true") to the KamajiControlPlane resource.
- Observe that the SveltosCluster loses its labels .

# System Information

CLUSTERAPI VERSION: ` v1.10 `
SVELTOS VERSION: ` 0.53.0 `
KUBERNETES VERSION: ` v1.31`

# LOGS
I couldn't find any relevant logs in the EventManager Pod
