### ISSUE TITLE
EventBasedAddOn with multiple PolicyRefs

### ISSUE THREAD

**Issue by gianlucam76** [projectsveltos/event-manager#94]
If we have an EventBasedAddOn with multiple PolicyRefs like following

```yaml
apiVersion: lib.projectsveltos.io/v1alpha1
kind: EventBasedAddOn
metadata:
 name: postgresql-job
spec:
 sourceClusterSelector: env=fv
 eventSourceName: postgresql-job
 policyRefs:
 - name: todo-deployment
   namespace: default
   kind: ConfigMap
 - name: todo-service
   namespace: default
   kind: ConfigMap
 - name: todo-ingress
   namespace: default
   kind: ConfigMap
```

The generated ClusterProfile will reference only one ConfigMap (instead of three).

Issue is within **instantiateReferencedPolicies**. If an EventBasedAddOn references multiple ConfigMaps, it takes content of each ConfigMap and then creates a new ConfigMap.

Name of the new ConfigMap is based on labels.

For instance labels added to ConfigMap created by event-manager for a given EventBasedAddOn and matching cluster are:

  labels:
    eventbasedaddon.lib.projectsveltos.io/clusterNamespace: default
    eventbasedaddon.lib.projectsveltos.io/clustername: clusterapi-workload
    eventbasedaddon.lib.projectsveltos.io/clustertype: Capi
    eventbasedaddon.lib.projectsveltos.io/eventbasedaddonname: postgresql-job
    
    
So in above EventBasedAddOn example, for each referenced ConfigMap (there are 3) instantiateReferencedPolicies will try to create three new ConfigMaps. But name will always be same. So only one ConfigMap will be created and its content will be the ones of the latest referenced ConfigMap (todo-ingress in this example)
